name: CI

on:
  push:
    branches: [ "release/*" ]
  pull_request:
    branches: [ "release/*" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:          
    - uses: actions/checkout@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: shordinger1/cicdtest:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
